[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[program:octane]
command=php /var/www/artisan octane:start --server=swoole --host=0.0.0.0 --port=8000
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_maxbytes=0
stderr_logfile=/dev/stderr
stderr_maxbytes=0

[program:scheduler]
command=php /var/www/artisan schedule:work
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_maxbytes=0
stderr_logfile=/dev/stderr
stderr_maxbytes=0

[program:worker]
command=php /var/www/artisan queue:work redis --sleep=3 --tries=3
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_maxbytes=0
stderr_logfile=/dev/stderr
stderr_maxbytes=0
